### ISSUE TITLE
Missing theme-gcwu-gegc release v4.0.23

### ISSUE THREAD

**Issue by sylus** [wet-boew/themes-cdn#3]
It seems there is a missing theme-gcwu-gegc release for v4.0.23

**Comment by nschonni** [comment]
https://github.com/wet-boew/theme-gcwu-fegc hasn't been tagged yet

**Comment by TTVXStarWake** [comment]
i will tag and close this theme today

**Comment by TTVXStarWake** [comment]
Available to download http://wet-boew.github.io/v4.0-ci/docs/versions/dwnld-en.html
