### ISSUE TITLE
Missing themes for release 4.0.28 and 4.0.28.1?

### ISSUE THREAD

**Issue by nathanpw** [wet-boew/themes-cdn#4]
This appears to be the same issue reported in https://github.com/wet-boew/themes-cdn/issues/3

The following assets are missing for 4.0.28 and 4.0.28.1?

https://github.com/wet-boew/themes-cdn/archive/v4.0.28.1-theme-base.tar.gz
https://github.com/wet-boew/themes-cdn/archive/v4.0.28.1-theme-gc-intranet.tar.gz
https://github.com/wet-boew/themes-cdn/archive/v4.0.28.1-theme-gcwu-fegc.tar.gz
https://github.com/wet-boew/themes-cdn/archive/v4.0.28.1-theme-ogpl.tar.gz

**Comment by nathanpw** [comment]
@duboisp can you help with this since you tagged the last 2 releases?

**Comment by duboisp** [comment]
@nathanpw thanks for tagging me, I wasn't aware of this issue.

To answer at your question, no this is not an issue. I dropped the support for those theme. See the discussion here: https://github.com/wet-boew/wet-boew/issues/8366 

I would also recommend to use the release 4.0.28.1 and not 4.0.28. The form validation plugin don't work with 4.0.28 but work fine with 4.0.28.1

I saw that you recently contributed to the wet-boew Drupal variant, I am interested to know how that project is going. Are you available on July 26 afternoon? It's the WET Roadmap meeting. It's a monthly meeting where we gather an update from all the projects related wet-boew. Let me know. 😃

**Comment by nathanpw** [comment]
@duboisp thanks for letting me know. Not really sure how to proceed with this news. We had Drupal integratons for all these themes. Your readme still indicates you support 5 themes https://github.com/wet-boew/wet-boew/blob/master/README.md and so do your docs http://wet-boew.github.io/wet-boew/docs/ref/themesstyle-en.html . Would be nice if there was broader notification with more advanced notice before these themes were completely dropped.

I might be available July 26th, I will contact you via email.

**Comment by duboisp** [comment]
I will update those file next week.

The WET Roadmap meeting, next on July 26, is how I advertised it. I also opened an issue on github about it. If you can make it on July 26th or by email, we can also discuss how we can improve the communication between our team.

The main issue for those theme is there is no resource that can maintain it.

**Comment by LaurentGoderre** [comment]
I'm a bit concerned about the language used in this thread ("I dropped", "I announced"). It gives the impression that they were unilateral decisions. 

I created a full set of tools to automate the release process so creating releases for those themes should not be more than half an hour on what is already a quarterly occurrence

**Comment by duboisp** [comment]
@LaurentGoderre the rational is explained in wet-boew/wet-boew#8366

I am sorry if the wording I used in my previous comments in this post offend you.

> I created a full set of tools to automate the release process so creating releases for those themes should not be more than half an hour on what is already a quarterly occurrence

Yes but today those build script need to be upgraded for a better compatibility with the latest version of NodeJS and development work is needed to replicated some of the latest changes we have made for the wet-boew theme and the gcweb theme. Feel free to express your interest to maintain it by commenting in wet-boew/wet-boew#8366

Cheers
